# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Notes
copyright: These are my public notes

repo_name: acceptilation/notes
repo_url: https://github.com/acceptilation/notes

plugins:
  - privacy
  - git-revision-date-localized:
      type: timeago
  - git-committers:
      repository: acceptilation/notes
      branch: main

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true

nav:
  - Home: index.md
  - Reference:
      - Concourse: concourse.md
      - JetBrains: jetbrains.md
  - Setup:
      - Azure Functions App: azure-functions-app.md
      - GitHub Repository: github-repository.md
      - Remote Redis Connection: remote-redis-connection.md
      - Safe: safe.md
      - Sonar: sonar.md

extra:
  social:
    - name: BibleProject
      link: https://bibleproject.com
      icon: material/chat

    - name: Christianity Today
      link: https://www.christianitytoday.com
      icon: material/circle-opacity

    - name: Church of the Redeemer
      link: https://www.redeemeratlanta.org
      icon: material/cross-bolnisi

    - name: The Gospel Coalition
      link: https://www.thegospelcoalition.org
      icon: material/square

theme:
  name: material
  favicon: favicon.io.emoji-favicons.notebook.png
  icon:
    logo: material/note-text
  features:
    - content.code.annotate
    - navigation.sections

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
