# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Notes
copyright: These are my notes,

repo_name: GitHub Pages
repo_url: https://github.com/acceptilation/acceptilation.github.io
edit_uri: edit/main/docs/

plugins:
  - git-committers:
      repository: acceptilation/acceptilation.github.io
      branch: main
  - git-revision-date-localized:
      type: timeago
  - privacy
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Reference:
      - Concourse: reference/concourse.md
      - JetBrains: reference/jetbrains.md
      - Python-Kafka: reference/python-kafka.md
  - Setup:
      - Azure Functions App: setup/azure-functions-app.md
      - GitHub Repository: setup/github-repository.md
      - Remote Redis Connection: setup/remote-redis-connection.md
      - Safe: setup/safe.md
      - Sonar: setup/sonar.md

extra:
  social:
    - name: BibleProject
      link: https://bibleproject.com
      icon: material/chat

    - name: Christianity Today
      link: https://www.christianitytoday.com
      icon: material/circle-opacity

    - name: Church of the Redeemer
      link: https://www.redeemeratlanta.org
      icon: material/cross-bolnisi

    - name: The Gospel Coalition
      link: https://www.thegospelcoalition.org
      icon: material/square

theme:
  name: material
  favicon: favicon.io.emoji-favicons.notebook.png
  icon:
    logo: material/note-text
    repo: material/github
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - navigation.sections
    - search.suggest

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
